### PR TITLE
Handle UTF-8 issues

### PR DESCRIPTION
**Pull request by SilenceZen**
Use chardet can get file encoding.  So I think maybe use this package for automatic matching

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
while this is possibly a nice to have, its also a breaking change in terms of behaviour, and needs a extra dependency

based on licensing i'm not keen on adding chardet here

**Comment by SilenceZen** [comment]
May I use RE for UTF-8 compatibility？

**Comment by RonnyPfannschmidt** [comment]
RE?

**Comment by SilenceZen** [comment]
year。regular    re.compile

**Comment by RonnyPfannschmidt** [comment]
I'm inclined to have support for something like a coding comment that python had and/or coordinating a utf8 default in coordination with pytest

What's your surrounding usecase?

**Comment by SilenceZen** [comment]
I tried to change the contents of the file when I use chardet to test. And I found, IEDA recognized the file with Chinese as UTF-8 when I did not set the file encoding to ANSI and use Chinese

**Comment by SilenceZen** [comment]
I think exposing the encoding as input parameter is not good. Pytest may be need to change obecause  the reading that pytest does, not the user.

**Comment by SilenceZen** [comment]
obecause = because.

**Comment by RonnyPfannschmidt** [comment]
Then it is critical to ensure that pytest does the change in a controlled manner to begin with

Cc @nicoddemus

Im also a maintainer of pytest and happy to assist

**Comment by SilenceZen** [comment]
Haha.  The pytest configuration file is only pytest.ini.  Pytest may be need to open it again if the encoding format is in the INI

**Pull request closed without merging**
