### PR TITLE
Add support for Python 3.12-3.13 and drop EOL 3.7

### PR DESCRIPTION
**Pull request by hugovk**
The [Python 3.12 release candidate](https://discuss.python.org/t/python-3-12-0-release-candidate-1-released/31137?u=hugovk) is out! :rocket:

> ## Call to action
> 
> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.12 compatibilities during this phase, and where necessary publish Python 3.12 wheels on PyPI to be ready for the final release of 3.12.0.

See also https://dev.to/hugovk/help-test-python-312-beta-1508/

### CODE REVIEW

**Review by RonnyPfannschmidt — APPROVED** [review]
lovely, thanks

**Comment by hugovk** [comment]
11 months later, updated to add support for Python 3.13, now the 3.13 RC is out :)

**Comment by hugovk** [comment]
This is now a year old, when I usually close still-open PRs. Or can we merge this? :)

**Comment by RonnyPfannschmidt** [comment]
I just noted I never submitted the review, let's merge and do cleanup later

**Pull request merged**
